version: '3.4'

networks:
  soen390-team01-network:
    driver: bridge 

services:
  soen390-team01:
    image: ${DOCKER_REGISTRY-}soen390team01
    depends_on:
      - "postgres"
    build:
      context: .
      dockerfile: soen390-team01/Dockerfile
    ports:
    - "5000:80"
    environment:
      HOST: host.docker.internal
      DB_CONNECTION_STRING: "host=host.docker.internal;port=5431;database=soen390team01devdb;username=soen390team01devuser;password=soen390team01devpassword;SSL Mode=Require;Trust Server Certificate=true"
      ENCRYPTED_KEY: "6hk2V97Vhgj4fhYqKtgdFZOtl8uu4E/3+udFPap+qTg="
      ENCRYPTED_IV: "AYiCikByeIU//DNhVg5Bpg=="
      TZ: "America/Toronto"
    networks:
      - soen390-team01-network  
  
  postgres:
    image: postgres:latest
    command: -c ssl=on -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    ports:
      - "5431:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "soen390team01devuser"
      POSTGRES_PASSWORD: "soen390team01devpassword"
      POSTGRES_DB: "soen390team01devdb"
    networks:
      - soen390-team01-network

volumes:
  db_volume: